[general]
# Video width and height in pixels
width = 1920
height = 1080
# Frames per second, higher is faster (can be fractional)
fps = 2

# Text to display on an intro screen (empty to disable)
intro_text = ""
# Time to show the intro screen, in seconds (ignored if text is empty)
intro_time = 5
# Whether to show a watermark in the bottom-right corner
watermark = true

[sizes]
# These are fractions of the full sizes
code_width = [2, 3]
code_height = [4, 5]
last_variable_height = [1, 4]

# Padding
heading_padding = 20
section_padding = 20

# Line height (multiplier of the font size)
line_height = 1.2

[fonts]
# Paths that start with $VARDBG are relative to the debugger's root directory
# Sizes are in pixels

# Font used for the main code body (including a bold version)
body = "$VARDBG/fonts/FiraMono-Regular.ttf"
body_bold = "$VARDBG/fonts/FiraMono-Bold.ttf"
body_size = 16

# Caption font, used to show execution times below the code as well as the watermark
caption = "$VARDBG/fonts/Inter-Regular.ttf"
caption_size = 16

# Heading font, used to show headings in the variable sections
heading = "$VARDBG/fonts/Inter-Regular.ttf"
heading_size = 24

# Intro font, used to render the intro screen
intro = "$VARDBG/fonts/Inter-Bold.ttf"
intro_size = 48
